# Generated by Django 4.1.5 on 2023-01-03 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('prezzo_acqua', models.FloatField()),
                ('prezzo_secco', models.FloatField()),
                ('prezzo_sartoria', models.FloatField()),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('icona', models.CharField(max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('cognome', models.CharField(max_length=64)),
                ('telefono', models.CharField(max_length=16, null=True)),
                ('indirizzo', models.CharField(max_length=128, null=True)),
                ('note', models.CharField(max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
            },
        ),
        migrations.CreateModel(
            name='Colore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('icona', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Colore',
                'verbose_name_plural': 'Colori',
            },
        ),
        migrations.CreateModel(
            name='Difetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('icona', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Difetto',
                'verbose_name_plural': 'Difetti',
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_attuale', models.DateTimeField(auto_now=True)),
                ('data_ritiro', models.DateField()),
                ('totale', models.FloatField()),
                ('credito', models.FloatField()),
                ('domicilio', models.BooleanField()),
                ('stato', models.CharField(choices=[('NO', 'non_iniziato'), ('PA', 'pariziale'), ('CO', 'completato')], max_length=2)),
                ('note', models.CharField(max_length=256)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_cliente', to='detergo_gestionale_app.cliente')),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
            },
        ),
        migrations.CreateModel(
            name='CapoPortato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('NO', 'non_iniziato'), ('PA', 'pariziale'), ('CO', 'completato')], max_length=2)),
                ('prezzo_modificato', models.FloatField(null=True)),
                ('foto', models.CharField(max_length=256, null=True)),
                ('colore', models.ManyToManyField(to='detergo_gestionale_app.colore')),
                ('difetto', models.ManyToManyField(to='detergo_gestionale_app.difetto')),
                ('id_articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_articolo', to='detergo_gestionale_app.articolo')),
                ('id_ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_ordine', to='detergo_gestionale_app.ordine')),
            ],
            options={
                'verbose_name': 'CapoPortato',
                'verbose_name_plural': 'CapiPortati',
            },
        ),
        migrations.AddField(
            model_name='articolo',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_categoria', to='detergo_gestionale_app.categoria'),
        ),
    ]
