# Generated by Django 4.1.5 on 2023-01-07 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detergo_gestionale_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroughtItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('NS', 'not_started'), ('PA', 'partial'), ('CO', 'completed')], max_length=2)),
                ('price', models.FloatField(null=True)),
                ('photo', models.ImageField(blank=True, max_length=256, null=True, upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'BroughtItem',
                'verbose_name_plural': 'CarriedItems',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(blank=True, max_length=256, null=True, upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(blank=True, max_length=256, upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=16, null=True)),
                ('address', models.CharField(max_length=128, null=True)),
                ('notes', models.CharField(max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('icon', models.ImageField(blank=True, max_length=256, upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Defect',
                'verbose_name_plural': 'Defects',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('water_price', models.FloatField()),
                ('dry_price', models.FloatField()),
                ('tailoring_price', models.FloatField()),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_category', to='detergo_gestionale_app.category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateTimeField(auto_now=True)),
                ('pickup_date', models.DateField()),
                ('total', models.FloatField()),
                ('credit', models.FloatField()),
                ('domicile', models.BooleanField()),
                ('state', models.CharField(choices=[('NS', 'not_started'), ('PA', 'partial'), ('CO', 'completed')], max_length=2)),
                ('notes', models.CharField(max_length=256)),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_customer', to='detergo_gestionale_app.customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.RemoveField(
            model_name='capoportato',
            name='colore',
        ),
        migrations.RemoveField(
            model_name='capoportato',
            name='difetto',
        ),
        migrations.RemoveField(
            model_name='capoportato',
            name='id_articolo',
        ),
        migrations.RemoveField(
            model_name='capoportato',
            name='id_ordine',
        ),
        migrations.RemoveField(
            model_name='ordine',
            name='id_cliente',
        ),
        migrations.DeleteModel(
            name='Articolo',
        ),
        migrations.DeleteModel(
            name='CapoPortato',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Colore',
        ),
        migrations.DeleteModel(
            name='Difetto',
        ),
        migrations.DeleteModel(
            name='Ordine',
        ),
        migrations.AddField(
            model_name='broughtitem',
            name='color',
            field=models.ManyToManyField(to='detergo_gestionale_app.color'),
        ),
        migrations.AddField(
            model_name='broughtitem',
            name='defect',
            field=models.ManyToManyField(to='detergo_gestionale_app.defect'),
        ),
        migrations.AddField(
            model_name='broughtitem',
            name='id_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_item', to='detergo_gestionale_app.item'),
        ),
        migrations.AddField(
            model_name='broughtitem',
            name='id_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_order', to='detergo_gestionale_app.order'),
        ),
    ]
