# Generated by Django 4.1.5 on 2023-01-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detergo_gestionale_app', '0002_broughtitem_category_color_customer_defect_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, upload_to='uploads/'),
        ),
    ]
