# Generated by Django 4.1.5 on 2023-01-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detergo_gestionale_app', '0003_item_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
