# Generated by Django 4.1.5 on 2023-01-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detergo_gestionale_app', '0006_remove_broughtitem_defect_broughtitem_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='maxi',
            field=models.CharField(choices=[('LE', 'left'), ('RI', 'right')], max_length=2, null=True),
        ),
    ]
